version: '2'
services:
  mysql:
    image: mysql:5.5
    container_name: wc18-dev-mysql
    ports:
      - 3306:3306
    environment:
      MYSQL_DATABASE: "wc18"
      MYSQL_ROOT_PASSWORD: "mjeanroy"
    volumes:
      - ./.data/mysql:/var/lib/mysql
