##
# Copyright (C) Mickael Jeanroy - All Rights Reserved.
# Unauthorized copying of this file, via any medium is strictly prohibited.
# Proprietary and confidential.
##

version: '3'
services:
  backend:
    container_name: wc18-backend
    build: ../../wc18-back
    ports:
      - 8080:8080
    depends_on:
      - db
    env_file:
        - ~/.wc18/conf/env
  frontend:
    container_name: wc18-frontend
    build: ../../wc18-front
    ports:
      - 80:80
    depends_on:
      - backend
  db:
      image: mysql:5.5
      container_name: wc18-db
      ports:
        - 3306:3306
      env_file:
        -  ~/.wc18/mysql/env
      volumes:
        - ~/.wc18/data/mysql:/var/lib/mysql
